#!/bin/bash
#
echo "Sim Controller Update Version 1.1.7"
RED='\033[0;31m'
CYAN='\033[0;36m'
NC='\033[0m' # No Color

if ! id | grep -q root; then
	echo "must be run as root (use \"sudo scupdate\")"
	exit
fi

echo "stopping simctl service"
systemctl stop simctl

echo "Installing files"
cp simController /usr/local/bin
cp simCurl /usr/local/bin
cp ctlstatus.cgi /var/www/cgi-bin
chmod ug+s /var/www/cgi-bin/ctlstatus.cgi
cp rfidScan /usr/local/bin
cp cprScan  /usr/local/bin
cp pulse /usr/local/bin
cp breathSense /usr/local/bin
cp ain_air_test ainmon tsunami_test /usr/local/bin
cp soundSense /usr/local/bin
cp -r html /var/www

if [ ! -f /simulator/simmgrName ]
then
	echo "Installing default SimMgr configuration"
	cp simmgrName /simulator
else
	echo "SimMgr configuration file already exists"
fi

port=$(awk '!/^ *#/ && /40844/' /simulator/simmgrName)
if [[ ${#port} -eq 0 ]]
then
	port=$(awk '!/^ *#/ && /50200/' /simulator/simmgrName)
	if [[ ${#port} -eq 0 ]]
	then
		echo "No Port specified in /simulator/simmgrName"
	else
		echo -e "${RED}WARNING: Linux Port specified in /simulator/simmgrName${NC}"
		read -p "Replace with WinVetSim configuration? <Y/n> " prompt
		if [[ $prompt == "y" || $prompt == "Y" || $prompt == "yes" || $prompt == "Yes" ]]
		then
			echo "Installing default SimMgr configuration"
			cp simmgrName /simulator
		fi

	fi
else
	echo -e "${CYAN}WinVetSim Port specified in /simulator/simmgrName${NC}"
fi

echo "starting simctl service"
systemctl start simctl

echo "Update is complete"
