#!/bin/sh -x
### BEGIN INIT INFO
# Provides:          simctl
# Required-Start:    $local_fs $all
# Required-Stop:     $local_fs
# Default-Start:     5
# Default-Stop:      0 1 2 3 4 6
# Short-Description: Start daemon at boot time
# Description:       Enable service provided by daemon.
### END INIT INFO

. /lib/lsb/init-functions

do_status()
{
	status_of_proc /usr/local/bin/simController simController
	status_of_proc /usr/local/bin/pulse pulse
	status_of_proc /usr/local/bin/rfidScan rfidScan
	status_of_proc /usr/local/bin/soundSense soundSense
	status_of_proc /usr/local/bin/breathSense breathSense
	status_of_proc /usr/local/bin/cprScan cprScan
}


do_start()
{
	/usr/local/bin/simController
	sleep 2
	/usr/local/bin/pulse
	/usr/local/bin/rfidScan
	/usr/local/bin/soundSense ttyO2
	/usr/local/bin/breathSense
	/usr/local/bin/cprScan
	
}
do_stop()
{
	killall cprScan
	killall soundSense
	killall breathSense
	killall rfidScan
	killall pulse
	killall simController
}

case "$1" in
	start)
		do_start
		;;
	restart)
		do_stop
		do_start
		;;
	status)
		do_status
		;;
	stop)
		echo "Doing Stop"
		do_stop
		echo "Done"
		;;
	*)
		echo "Usage: /etc/init.d/simctl {start|stop|status|restart}"
		;;
esac

exit 0
